#
###################################
# Site wide configuration
####################################
#
title: GlitchWitch Security
keywords: ["Glitch Witch, GlitchWitch, Infosec, hacker, researcher, spooky hacker girl"]
url: https://glitchwitch.io
#url: http://127.0.0.1:4000

sass:
    sass_dir: _sass

collections:
  posts:
    output: true
    permalink: /blog/:year-:month/:title/
  pages:
    output: true
    permalink: /:path
  reports:
    output: true
    permalink: /:path
  services:
    output: true
    permalink: /:path

#
###################################
# Jekyll configuration
####################################
#
timezone:          UTC
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /blog/:year-:month/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
# Contact Info
  email: "hello@glitchwitch.io"
# APIs and other settings
  disqus-shortname: glitchwitchio
  google-analytics: #UA-XXXXXXXX-X
  rss: feed.xml
# Social
  twitter: GlitchWitch
  github: GlitchWitch
